
/* CRIANDO DATABASE */

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR (15) UNIQUE
);


CREATE TABLE ENDEREÇO (
	IDENDEREÇO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(15) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* ALIMENTANDO DATABASE (DML) */

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');


INSERT INTO ENDEREÇO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA ALFANDEGA','CENTRO','SAO PAULO','SP',5); /* ERRO DE ID PROPOSITAL PARA TESTE */
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',7);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',9);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',11);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDEREÇO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',13);
INSERT INTO ENDEREÇO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',14);
INSERT INTO ENDEREÇO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',15);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',16);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',17);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',18);
INSERT INTO ENDEREÇO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',19);



INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',9);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',9);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',10);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',13);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',14);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',15);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',16);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',19);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',19);

/* NOME, SEXO APENAS DE MULHERES, BAIRRO, CIDADE (JUNÇÃO DE TABELAS) */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDEREÇO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';

/* NOME, SEXO, EMAIL, TIPO, NÚMERO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
WHERE TIPO = 'CEL';

/* EXERCÍCIO -> RETORNAR APENAS NOME (FORMATO NOME_PARTICIPANTE) EM ORDEM ALFABÉTICA
COM SEXO E TELEFONE*/

SELECT NOME AS NOME_PARTICIPANTE, SEXO, NUMERO AS TELEFONE
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
ORDER BY NOME_PARTICIPANTE;

/* EXERCICIO -> RETORNAR NOME, QUANTIDADE DE TELEFONE, E ORDENAR
POR QUANTIDADE MAIOR DE TELEFONE */

SELECT NOME, COUNT(NUMERO) AS TELEFONE
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
GROUP BY NOME
ORDER BY NUMERO DESC;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO (JUNÇÃO DE 3 TABELAS) */

SELECT CL.NOME,CL.SEXO,EN.BAIRRO,EN.CIDADE,TE.TIPO,TE.NUMERO
FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE;


/* RELATÓRIO GERAL DE TODOS OS CLIENTES */

SELECT * FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE;

/* RELATÓRIO DE HOMENS */

SELECT * FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE
WHERE CL.SEXO = 'M';

/* UPDATE DE DADO ERRADOS (SEXO TROCADO) */

10, 11, 16, 17

SELECT * FROM CLIENTE
WHERE IDCLIENTE IN (10,11,16,17);

UPDATE CLIENTE SET SEXO = 'F'
WHERE IDCLIENTE IN (10,11,16,17);

/* RELATÓRIO DE MULHERES */

SELECT * FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE
WHERE CL.SEXO = 'F';

/* UPDATE DE DADO ERRADOS (SEXO TROCADO) */

UPDATE CLIENTE SET SEXO = 'M'
WHERE IDCLIENTE IN (14);

/* RELATORIO DE QUANTIDADE DE HOMENS E MULHERES */

SELECT SEXO, COUNT(SEXO) AS QUANTIDADE
FROM CLIENTE
GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RJ E QUE
NÃO TENHAM EMAIL */

SELECT CL.IDCLIENTE,CL.NOME,CL.EMAIL,CL.SEXO,EN.BAIRRO,TE.NUMERO
FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE
WHERE CL.SEXO = 'F' AND EN.BAIRRO = 'CENTRO'
AND EN.CIDADE = 'Rio de Janeiro'
AND CL.EMAIL IS NULL;

/* USANDO FUNÇÃO IFNULL */

SELECT CL.IDCLIENTE,CL.NOME,IFNULL(CL.EMAIL,'VAZIO') AS EMAIL,CL.SEXO,EN.BAIRRO,TE.NUMERO
FROM CLIENTE CL
INNER JOIN ENDEREÇO EN
ON CL.IDCLIENTE = EN.ID_CLIENTE
INNER JOIN TELEFONE TE
ON CL.IDCLIENTE = TE.ID_CLIENTE;
